# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('comentarios', models.TextField()),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('historico_ph', models.FileField(upload_to=b'')),
                ('historico_lux', models.FileField(upload_to=b'')),
                ('historico_temp_agua', models.FileField(upload_to=b'')),
                ('historico_temp_ar', models.FileField(upload_to=b'')),
            ],
        ),
    ]
