# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 20, 0, 52, 123986), editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_lux',
            field=models.FileField(editable=False, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_ph',
            field=models.FileField(editable=False, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_temp_agua',
            field=models.FileField(editable=False, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_temp_ar',
            field=models.FileField(editable=False, upload_to=b''),
        ),
    ]
