# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_auto_20171022_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 18, 8, 23, 659155), editable=False),
        ),
    ]
