# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_auto_20171022_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 18, 25, 14, 311033)),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_lux',
            field=models.FileField(upload_to='./historico/imagem2.png'),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_ph',
            field=models.FileField(upload_to='./historico/imagem1.png'),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_temp_agua',
            field=models.FileField(upload_to='./historico/imagem3.png'),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_temp_ar',
            field=models.FileField(upload_to='./historico/imagem4.png'),
        ),
    ]
