# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0006_auto_20171023_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 13, 59, 48, 170857)),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_lux',
            field=models.FileField(upload_to='./historico/lux'),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_ph',
            field=models.FileField(upload_to='./historico/ph'),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_temp_agua',
            field=models.FileField(upload_to='./historico/temp_agua'),
        ),
        migrations.AlterField(
            model_name='post',
            name='historico_temp_ar',
            field=models.FileField(upload_to='./historico/temp_ar'),
        ),
    ]
