# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0020_auto_20171024_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 14, 39, 23, 48926)),
        ),
    ]
