# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0021_auto_20171024_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 14, 43, 46, 857965)),
        ),
    ]
