# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0024_auto_20171024_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 15, 1, 53, 170687)),
        ),
    ]
